spring:
  application:
    name: vidalink

  profiles:
    active: prod

  api:
    security:
      secret:
        key: ${SECRET}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    show-sql: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  path: /data/images

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true