# application-prod.yml
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurações de logging para produção
logging:
  level:
    com.vidalink: INFO
    org.springframework.security: WARN
  file:
    name: /app/logs/vidalink-prod.log

# Configurações de segurança
server:
  error:
    include-message: never
    include-binding-errors: never